name: Simple Pipeline

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you need

      - name: Multiline Commands
        run: |
          node -v
          npm -v
